name: flutter_riverpod
description: DI and State management lib.
version: 2.6.1
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.4.0
  collection: ^1.15.0

  riverpod:
    path: ../riverpod

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  stack_trace: ^1.0.0
